name: main
on:
  pull_request:
  push:
    branches: [master, main, 'test-me-*']
    tags: ['*']

jobs:
  main-windows:
    uses: asottile/workflows/.github/workflows/tox.yml@v1.11.1
    with:
      env: '["py311"]'
      os: windows-latest
  main-linux:
    uses: asottile/workflows/.github/workflows/tox.yml@v1.11.1
    with:
      env: '["pypy3", "py311", "py312", "py313", "py314", "py315"]'
      os: ubuntu-latest
  main-other:
    uses: asottile/workflows/.github/workflows/tox.yml@v1.11.1
    with:
      env: '["flake8"]'
      os: ubuntu-latest
